version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-opswork-demo
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
